apiVersion: apps/v1
kind: Deployment
metadata:
  name: zelt-locust-worker
  namespace: zelt
  labels:
    application: zelt-locust
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      application: zelt-locust
      role: worker
  template:
    metadata:
      labels:
        application: zelt-locust
        role: worker
    spec:
      initContainers:
      - name: init-locust-controller-ready
        image: busybox
        command: ['sh', '-c', 'until nc -vz -w 3 zelt-service 8089; do echo waiting for Locust Controller; sleep 2; done;']
        resources:
          limits:
            memory: 100Mi
      containers:
        - name: locust
          image: registry.opensource.zalan.do/automata/locust
          resources:
            requests:
              cpu: 0.25
              memory: 100Mi
            limits:
              memory: 100Mi
          # Note that the "master/slave" terminology here is from Locust.
          # We refer to them as "controller" and "worker" respectively.
          command: ["locust", "--host", "unused", "--slave", "--master-host", "zelt-service", "-f", "/app/locustfile.py"]
          volumeMounts:
            - name: config-volume
              mountPath: /app
      volumes:
        - name: config-volume
          configMap:
            name: zelt-locustfile
