version: "2017-09-20"
pipeline:
  - id: Build
    type: script
    vm: small
    overlay: ci/python
    commands:
      - desc: "Dependencies"
        cmd: |
          apt-get update
          apt-get install -y python3.6-venv
          pip install poetry

      - desc: "Install"
        cmd: |
          make install

      - desc: "Test"
        cmd: |
          make test

      - desc: "Lint"
        cmd: |
          make lint

      - desc: "Upload code quality data to SonarQube"
        cmd: |
          sonar-client \
            -Dsonar.sources=zelt \
            -Dsonar.exclusions=main.py,tests/**/*.py,images \
            -Dsonar.python.pylint.reportPath=pylint-report.txt \
            -Dsonar.python.coverage.reportPath=coverage.xml \
            --recipes=update-dashboard-on-merge,pr-issues-as-comments,compare-pr-coverage
